springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  contextPath: /v1

spring.data.mongodb:
  host: localhost
  port: 27017
  database: caringheart
  
spring.jackson.serialization.write-dates-as-timestamps: false

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/mybatis
#    username: root
#    password: null
#    driver-class-name: com.mysql.jdbc.Driver
