springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  contextPath: /caringheart-backend

spring.data.mongodb:
  host: localhost
  port: 27017
  database: caringheart
  
spring.jackson.serialization.write-dates-as-timestamps: false

spring.application.name: mongodb-service
server.port: 9998
eureka.client.serviceUrl.defaultZone: http://localhost:9999/eureka/

jwt.secret: 123456789
